# Generated by Django 4.0.3 on 2022-03-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='content_id',
            new_name='content',
        ),
    ]
